/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: bbcd6a4c4047e58e486ad27da371e641)
interface __BaseEnv_Env {
	SITE_URL: "https://dunedinherald.com";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "SITE_URL">> {}
}
